// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proba.Server;

namespace Proba.Server.Migrations
{
    [DbContext(typeof(ProbaContext))]
    partial class ProbaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Greet.ProbaMessage", b =>
                {
                    b.Property<string>("Greeting")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Added");

                    b.Property<int>("Count");

                    b.Property<double>("Value");

                    b.HasKey("Greeting");

                    b.ToTable("Probas");
                });
#pragma warning restore 612, 618
        }
    }
}
